### ISSUE TITLE
Feature request: Kindly add 'record' option

### ISSUE THREAD

**Issue by Vulgaris-Viridis** [caspermeijn/onvifviewer#3]
No problems finding apps that can view live stream, but the one that can record the stream is damn near impossible to find. hikvision has a simple, few MB plugin that adds recording and viewing option for their IP cameras, but alas it only works on Win and Mac. Vlc can record live stream over rtsp with some heavy encoding, but that's far from ideal.

It appears that the only other way is setting up a zoneminder on a dedicated server just so i can view few lan ip cameras which is crazy..

**Comment by caspermeijn** [comment]
I understand your problem. However I don't have plans to add a record feature. If you or someone else want to develop this, then I am happy to merge it.

**Comment by Vulgaris-Viridis** [comment]
Sadly my C++ skills are still not good enough to attempt that project, otherwise i'd gladly do it. Let's hope someone sees this and decides to help.

**Comment by caspermeijn** [comment]
You could always solve that problem by hiring someone with those skills ;-)

**Comment by Vulgaris-Viridis** [comment]
If i wanted to pay for software i wouldn't be using Foss now wouldn't i :)? Besides it's cheaper and easier to buy a dedicated box or nvr than to hire someone to write an app.

**Comment by Vulgaris-Viridis** [comment]
As a matter of fact, that's exactly what i'm gonna do. Thanks though.

**Comment by caspermeijn** [comment]
I didn't meant to scare you away. I use FOSS for the freedom and I don't mind paying for it. I agree that would be cheaper.
Consider keeping the issue open, maybe someone comes along to do this work as you mentioned.

**Comment by Vulgaris-Viridis** [comment]
You didn't scare me away i simply realized i'm wasting time with this, already ordered NVR - problem solved. Thanks again.
